### ISSUE TITLE
can you leave you qq or wechat？

### ISSUE THREAD

**Issue by zz10001** [LTYUnique/DS-SFFNet#2]
Thanks for your great work，I have some question want to ask you，can you leave your contact details

**Comment by LTYUnique** [comment]
给我你的联系方式吧，谢谢。

**Comment by zz10001** [comment]
目前不需要了，非常感谢


发自我的iPhone

------------------ Original ------------------
From: LTYUnique ***@***.***&gt;
Date: 周五,11月 19,2021 15:22
To: LTYUnique/DS-SFFNet ***@***.***&gt;
Cc: zz10001 ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [LTYUnique/DS-SFFNet] can you leave you qq or wechat？ (#2)





 
给我你的联系方式吧，谢谢。
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
